import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useData } from '../context/DataContext';
import { formatTime } from '../lib/utils';
export function Settings() {
    const { prefs, setPrefs, lastUpdated, refresh } = useData();
    function update(key, val) {
        setPrefs({ ...prefs, [key]: val });
    }
    return (_jsxs("div", { className: "h-full bg-black scrollable", style: { overflowY: 'auto' }, children: [_jsxs("div", { className: "px-5", style: { paddingTop: 'max(28px, env(safe-area-inset-top))' }, children: [_jsx("h1", { className: "text-[28px] font-semibold tracking-tight mb-8", style: { color: 'rgba(255,255,255,0.92)' }, children: "Settings" }), _jsxs("div", { className: "mb-8", children: [_jsx("p", { className: "text-[11px] font-semibold uppercase tracking-widest mb-1.5", style: { color: 'rgba(255,255,255,0.3)' }, children: "Risk tolerance" }), _jsx("p", { className: "text-xs mb-3", style: { color: 'rgba(255,255,255,0.38)' }, children: "Affects which coins surface as opportunities." }), _jsx("div", { className: "flex gap-1.5 p-1.5 rounded-2xl", style: { background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.08)' }, children: ['conservative', 'balanced', 'aggressive'].map((opt) => (_jsx("button", { onClick: () => update('riskTolerance', opt), className: "flex-1 py-2 rounded-xl text-sm font-medium transition-all capitalize", style: prefs.riskTolerance === opt
                                        ? { background: 'rgba(255,255,255,0.92)', color: '#000' }
                                        : { color: 'rgba(255,255,255,0.42)' }, children: opt }, opt))) }), _jsx("p", { className: "text-xs mt-2", style: { color: 'rgba(255,255,255,0.28)' }, children: prefs.riskTolerance === 'conservative'
                                    ? 'Only the clearest, highest-confidence setups.'
                                    : prefs.riskTolerance === 'balanced'
                                        ? 'A balance of opportunity and caution.'
                                        : 'More signals surfaced — higher risk, higher potential.' })] }), _jsxs("div", { className: "mb-8", children: [_jsx("p", { className: "text-[11px] font-semibold uppercase tracking-widest mb-1.5", style: { color: 'rgba(255,255,255,0.3)' }, children: "Coins to analyse" }), _jsx("p", { className: "text-xs mb-3", style: { color: 'rgba(255,255,255,0.38)' }, children: "Top coins by market cap. More coins = slightly slower load." }), _jsx("div", { className: "flex gap-1.5 p-1.5 rounded-2xl", style: { background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.08)' }, children: [10, 20, 30].map((n) => (_jsxs("button", { onClick: () => update('coinsToTrack', n), className: "flex-1 py-2 rounded-xl text-sm font-medium transition-all", style: prefs.coinsToTrack === n
                                        ? { background: 'rgba(255,255,255,0.92)', color: '#000' }
                                        : { color: 'rgba(255,255,255,0.42)' }, children: ["Top ", n] }, n))) })] }), _jsxs("div", { className: "mb-8", children: [_jsx("p", { className: "text-[11px] font-semibold uppercase tracking-widest mb-3", style: { color: 'rgba(255,255,255,0.3)' }, children: "Data sources" }), _jsx("div", { className: "rounded-2xl overflow-hidden", style: { background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.08)' }, children: [
                                    { label: 'Price & market data', value: 'CoinGecko (live)' },
                                    { label: 'Market sentiment', value: 'alternative.me (live)' },
                                    { label: 'Analysis', value: 'Computed on-device' },
                                ].map(({ label, value }, i, arr) => (_jsxs("div", { className: "flex justify-between items-center px-4 py-3.5", style: i < arr.length - 1 ? { borderBottom: '1px solid rgba(255,255,255,0.05)' } : {}, children: [_jsx("p", { className: "text-sm", style: { color: 'rgba(255,255,255,0.65)' }, children: label }), _jsx("p", { className: "text-xs", style: { color: 'rgba(255,255,255,0.35)' }, children: value })] }, label))) })] }), _jsxs("div", { className: "mb-4 text-center", children: [_jsx("p", { className: "text-xs mb-4", style: { color: 'rgba(255,255,255,0.25)' }, children: lastUpdated ? `Last refreshed at ${formatTime(lastUpdated)}` : 'Not yet loaded' }), _jsx("button", { onClick: refresh, className: "w-full py-3.5 rounded-2xl text-sm font-medium transition-opacity active:opacity-60", style: { background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.1)', color: 'rgba(255,255,255,0.7)' }, children: "Refresh all data now" })] }), _jsx("p", { className: "text-center text-[11px] mt-6", style: { color: 'rgba(255,255,255,0.18)' }, children: "Data refreshes automatically every 5 minutes." })] }), _jsx("div", { className: "pb-nav" })] }));
}
